apiVersion: v1
kind: Service
metadata:
  name: nginx-svc

spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nareunhang/test:finalFront
        imagePullPolicy: Always
        volumeMounts:             # 여기에 넣어줄거면 nareunhang/test:finalFront, 주석처리 할거면 nareunhang/test:middleFront1
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: my-nginx-config

